### PR TITLE
MIG-4: Create Navbar

### PR DESCRIPTION
**Pull request by moneymornings**
- Created logo
- Created Navbar
- Moved Toggle button/drop down to the right of the screen
- Created "meet the team button" as a placeholder for now, that we can develop on later to connect to our markdown page

### CODE REVIEW

**Review by Hoang-J — APPROVED** [review]
This is a cute logo picture!

**Comment by Hoang-J** [comment]
I think for now the code is good. I'm just not sure how it might look when both your and Gabe's code is merged into main since the codes are in the same location.

**Review by estradagabe1996 — APPROVED** [review]
looks good!

**Review by Hoang-J — APPROVED** [review]

**Comment by Hoang-J** [comment]
Good fix!

**Pull request merged**
